- src/app.rs
- src/jobs.rs
If set, this will be run after a sucessful publish operation.
We want to use this in flathub to purge the caches on the cdn.
> Add a per-repo post-publish-script option

- .travis.yml
This repo needs to be enabled on https://travis-ci.com before merging
> Add config for travis-ci

- src/api.rs
I think as this is unset, the build repos are defaulting to the ostree default of 3% which is actually a remarkably large amount of space on a 1TB volume:
```
Apr 18 13:46:42 hub.flathub.org flat-manager[30875]: WARN 2019-04-18T13:46:42Z: actix_web::pipeline: Error occurred during request handling: WrongRepoState(ready): Build failed: InternalError: Command "flatpak" "build-commit-from" "--timestamp=NOW" "--no-update-summary" "--untrusted" "--force" "--disable-fsync" "--gpg-homedir=/srv/gpg/agent" "--gpg-sign=4184DD4D907A7CAE" "--src-repo=/srv/repo/builds/2314/upload" "--src-ref=c7223e23cdf60061c58a499d4c0fa8495d894cd56d42f28f780ba06cd209b83f" "/srv/repo/builds/2314" "screenshots/i386" exited unsuccesfully: error: min-free-space-percent '3%' would be exceeded
```
> api: Set min-free-space-size=500MB on build repos

- src/app.rs
- src/jobs.rs
In preparation for Flathub deploying collection IDs to users, add the
DeployCollectionID key to generated flatpakref files. Although only
Flatpak >= 1.0.6 will honor it, older versions will ignore it without
producing an error.
The addition of DeployCollectionID to the flatpakrepo file and
ostree.deploy-collection-id to the repo metadata will have to be made
manually.
> jobs: Add DeployCollectionID key to flatpakref

- src/api.rs
- src/bin/delta-generator-client.rs
- src/jobs.rs
- src/ostree.rs
This supercharges the code in ostree for parsing gvariants. I want to use this in https://github.com/flatpak/flat-manager/pull/19 rather than linking to glib.
> Add various ostree helpers

- flat-manager-client
Switch to aiohttp to workaround `requests` reading entire file sooner or later instead of chunking.
Delta part is in separate branch as I still haven't figured out why flat-manager rejects their filenames. This PR is already deployed to production so it makes sense to me to merge it to master.
> client: Upload objects using aiohttp

- flat-manager-client
- src/api.rs
- src/app.rs
- src/db.rs
- src/errors.rs
- src/jobs.rs
- src/logger.rs
- src/models.rs
- src/ostree.rs
- src/tokens.rs
This is an alternative version of https://github.com/flatpak/flat-manager/pull/19
and builds on the flatpak work here: https://github.com/flatpak/flatpak/pull/3167
This assumes that some commits in the repo can have the xa.token-type set to a value != 0, and if so the flatpak authentication machinery will call into the authenticator api and can (optionally) return a bearer token that flatpak will pass when downloading the ref. The idea is that the authenticator can handle tokens differently. Some may be optional like donation requests, and trigger some nagging, but not actually send a token, whereas others do cause a token to be sent.
On the server side you can set the new `require-auth-for-token-types` option for the repo to a list of which token types require authentication. …
> Support requiring tokens for some refs

- src/app.rs
At Endless we have repos organized into staging subdirectories, but the
repo resource was only allowing a single path element. This changes the
parameter to a single glob and then walks backwards to find a repo name
that matches a path prefix.
> repo: Allow /s in repo names

- flat-manager-client
For manager url with a base directory, like https://site/some/path,
calling urljoin with absolute path would replace existing path in
URL. Change the API url with relative path to allow pass a manager
URL with a base path.
> Allow passing the manager URL with a base path

- src/jobs.rs
Post-publish is expected to be the final step of build processing.
> jobs: Extract appstream before running post-publish script

- .github/workflows/ci.yml
- tests/Dockerfile
- tests/README.md
- tests/config.json
- tests/docker-compose.yml
- tests/gen-key.sh
- tests/hello.sh
- tests/org.flatpak.FlatManagerCI.metainfo.xml
- tests/org.flatpak.FlatManagerCI.yml
- tests/run-test.py
Add a test that runs flat-manager and postrges using docker-compose, and then builds, uploads, and downloads a trivial app. The test takes about 10 minutes.
> Add end-to-end test

- tests/Dockerfile
The Debian-based image has an old version of libostree that makes everything more difficult when rewriting commits.
> ci: Run end-to-end test in Fedora

- src/errors.rs
The render_response implementation was missing, so it defaulted to a plain text error message.
> Fix JSON error messages

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/bin/flat-manager.rs
- src/db.rs
- src/lib.rs
Add futures 0.3 so we can use async/await. For now, futures 0.1 and 0.3 are both used, and actix-web is not updated to 4.0 yet.
> Add futures 0.3 and use async/await in some places

- flat-manager-client
This bumps requirement to Python 3.7
> Fix deprecation warning and use asyncio.run

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/api.rs
- src/app.rs
- src/bin/delta-generator-client.rs
- src/deltas.rs
- src/jobs.rs
- src/lib.rs
- src/models.rs
- src/ostree.rs
- src/storefront.rs
If this configuration option is present, this endpoint will be used to get information about each app when it is uploaded. It can be used to validate or modify appstream files and to set the token type of the commit.
Depends on #69.
> Add storefront-info-endpoint configuration

- flat-manager-client
- migrations/2022-08-05-212616_add_build_app_id/down.sql
- migrations/2022-08-05-212616_add_build_app_id/up.sql
- migrations/2022-09-06-002415_add_build_public_download/down.sql
- migrations/2022-09-06-002415_add_build_public_download/up.sql
- src/api.rs
- src/app.rs
- src/bin/delta-generator-client.rs
- src/bin/gentoken.rs
- src/db.rs
- src/deltas.rs
- src/jobs.rs
- src/models.rs
- src/ostree.rs
- src/schema.rs
- src/tokens.rs
Adds an optional app ID field to builds. Builds with an app ID require that app ID to be present in the token's `prefixes` field, protecting them from other users.
This change doesn't affect existing build tokens or processes, but once it is merged, build processes should be updated to create their builds with an app ID.
Also adds private builds, which also require a token to download from the build repo.
> Add optional app ID to builds

- flat-manager-client
This change decorates all functions which can raise ApiError with `@retry`, using "random" exponential wait between retries for up to 60s between each retry. If API request fails for 5 minutes, the client will re-raise the exception and quit.
> flat-manager-client: Retry all failed API requests

- flat-manager-client
flat-manager seems to return a JSON of string with actual JSON response, let's apply some duct tape on it
> client: Make sure /publish response is properly loaded into dict

- src/api.rs
- src/app.rs
- src/jobs.rs
- src/lib.rs
- src/ostree.rs
- src/tokens.rs
Adds an `apps` field to repo tokens. `has_token_prefix` checks it in addition to the `prefixes` field, but only for exact matches. This will allow us to, for example, give access to an app but not its extensions.
> Add token field for exact app matches

- README.md
- src/bin/delta-generator-client.rs
set `CDN_URL` to set the CDN url to download delta from
@barthalion this is based on your patch.
Note: it has been poorly tested.
> delta-generator-client: add CDN_URL env to set the cdn to download deltas from

- .github/workflows/ci.yml
- Bump the `actions/checkout` version to `v3` (To fix Node 12 deprecation warnings under Annotations in Actions).
- Bump `docker/build-push-action` to `v4`.
A test run of these changes can be found here on my fork https://github.com/kbdharun/flat-manager/actions
> ci.yml: bump checkout version to v3, build-push-action to v4

- Cargo.lock
- Cargo.toml
- src/api/build.rs
- src/app.rs
- src/config.rs
- src/db.rs
- src/jobs/check_job.rs
- src/jobs/commit_job.rs
- src/jobs/job_executor.rs
- src/jobs/job_instance.rs
- src/jobs/job_queue.rs
- src/jobs/publish_job.rs
- src/jobs/republish_job.rs
- src/jobs/update_repo_job.rs
- src/jobs/utils.rs
- src/lib.rs
- src/models.rs
- src/ostree.rs
- src/schema.rs
- src/tokens.rs
The remaining ones are somehow related to actix & futures usage
> Bump some of the deps

- flat-manager-client
> flat-manager-client: Non-zero exit code on job failure

- Dockerfile
Fixes #90
A possible alternative would be to change flat-manager to use gpg.
https://github.com/flatpak/flat-manager/blob/f6ef84fc39659065c7323e7680adff20add9068a/src/app.rs#L27
> Add gpg2 symlink to dockerfile

- src/api/build.rs
- src/db.rs
- src/jobs/check_job.rs
This field is intended for a machine-readable description of the check's original results (separate from the status reason, which may change when the check is reviewed).
> review-check: Allow setting the check results

- README.md
- flat-manager-client
- migrations/2023-06-14-145148_build_log_url/down.sql
- migrations/2023-06-14-145148_build_log_url/up.sql
- src/api/build.rs
- src/app.rs
- src/db.rs
- src/jobs/publish_job.rs
- src/jobs/republish_job.rs
- src/models.rs
- src/schema.rs
When creating a build or a build ref, you can specify the URL to the build log. The publish hook will be able to insert this data into the appstream file.
> Add build log URL field to builds and build refs

- README.md
- flat-manager-client
- migrations/2023-06-14-145148_build_log_url/down.sql
- migrations/2023-06-14-145148_build_log_url/up.sql
- src/api/build.rs
- src/app.rs
- src/db.rs
- src/jobs/check_job.rs
- src/jobs/publish_job.rs
- src/jobs/republish_job.rs
- src/models.rs
- src/schema.rs
When flat-manager-client waits for the commit job, it also waits for check jobs.
Also, if the build has failed or is still validating, don't retry publishing it.
Depends on #100 and #107.
> flat-manager-client: Wait for check jobs

- Cargo.lock
- migrations/2023-03-31-195311_token_revocation/down.sql
- migrations/2023-03-31-195311_token_revocation/up.sql
- src/api/build.rs
- src/api/mod.rs
- src/api/tokens.rs
- src/app.rs
- src/config.rs
- src/db.rs
- src/models.rs
- src/schema.rs
- src/tokens.rs
For tokens with a "jti" field, query the database to see if the token has been revoked. Also, log the time it was last used, to help debug and/or recognize suspicious activity.
There are two new endpoints, to list tokens (so the backend can show the last used time and whether a token is revoked) and to revoke tokens. The idea is for the backend to keep its own record of which tokens belong to which users, and invoke these endpoints on their behalf with its own token.
I've also added a config option to allow tokens to be prefixed. This makes it easier to recognize tokens that have been accidentally published.
> Implement token revocation
